Kc fixed merge button
nss-evening-cohort-19/gitsub-teambeans pull request #39
Opened 2022-05-14 16:06 UTC by kennethchittaphong

2022-05-14 16:20 UTC, KLaw47 requested changes

2022-05-14 16:20 UTC, KLaw47 commented on index.html
>      <script type="module" src="scripts/fakedata.js"></script>
these dont need to be modules only main.js is a module

2022-05-14 16:20 UTC, KLaw47 commented on scripts/overviewCard.js
> -    renderToDom("#overviewContainer", domString);
I dont think we need a whole new container for every page, theres just the main content, (the pinned repos) and the formContent (the add a project)

2022-05-15 18:55 UTC, KLaw47 approved these changes

2022-05-15 21:46 UTC, merged

2022-06-04 15:38 UTC, ajawashington commented on scripts/eventListenerRepo.js
> +
Do not commit and push multiple empty lines...this will help avoid merge conflicts

2022-06-04 15:40 UTC, ajawashington commented on scripts/Overview.js
> +  pinEventListener();
A good way to use setTimeout!

2022-06-04 15:43 UTC, ajawashington commented on scripts/Overview.js
> +const clearCheck = () => {
YES! Checkboxes can be hard and this logic looks good!